AWSTemplateFormatVersion: 2010-09-09
Description: "The Cf-Stack for the ELb"
Parameters:
  Project:
    Type: String
  Repository:
    Type: String
  Stage:
    Type: String
  Suffix:
    Type: String
  #import from existing-stacks:
  VpcStackName:
    Type: String

Resources:
  SgALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub sgelb${Stage}${Suffix}
      GroupDescription: "Security-Group for the ELB"
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          Description: "ingress rule for tcp on port 80"
          FromPort: 80
          ToPort: 80
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}:VpcId
      Tags:
        - Key: "Name"
          Value: !Sub sg-elb-${Stage}-${Suffix}
        - Key: "Stage"
          Value: !Sub ${Stage}

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub alb-${Stage}-${Suffix}
      IpAddressType: ipv4
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref SgALB
      Subnets:
        - Fn::ImportValue: !Sub ${VpcStackName}:PublicSubnetA # public
        - Fn::ImportValue: !Sub ${VpcStackName}:PublicSubnetB
        - Fn::ImportValue: !Sub ${VpcStackName}:PublicSubnetC
      Tags:
        - Key: "Name"
          Value: !Sub sg-elb-${Stage}-${Suffix}
        - Key: "Stage"
          Value: !Sub ${Stage}

  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub tg-elb-${Stage}-${Suffix}
      HealthCheckEnabled: True
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/health"
      HealthCheckPort: "8080"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: "200"
      Protocol: HTTP
      Port: 8080
      Tags:
        - Key: "Name"
          Value: !Sub tg-elb-${Stage}-${Suffix}
        - Key: "Stage"
          Value: !Sub ${Stage}
      TargetType: "ip"
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}:VpcId

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ALB
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Order: 1
          Type: "forward"
          TargetGroupArn: !Ref AlbTargetGroup

Outputs:
  AlbArnOutput:
    Description: The Arn of the ALB
    Value: !Ref ALB
    Export:
      Name: !Sub ${AWS::StackName}:AlbARN
  TargetGroupArnOutput:
    Description: The Arn of the TargetGroup
    Value: !Ref AlbTargetGroup
    Export:
      Name: !Sub ${AWS::StackName}:TargetGroupARN
  AlbSecurityGroupIdOutput:
    Description: The Id of the SecurityGroup of the alb
    Value: !Ref SgALB
    Export:
      Name: !Sub ${AWS::StackName}:Alb-SG-Id
  ApplicationLoadBalancerDNSName:
    Description: DNS for Application Load Balancer
    Value: !GetAtt ALB.DNSName
    Export:
      Name: !Sub ${AWS::StackName}:Alb-DNS
